"""Exact classification of CH label maps (k1,k2,k3) on P = F_2^s minus U, modulo C2,
up to H = Stab(U) acting on columns, and up to permuting the three labels.

Levels: orbits of k1 in V_P/C2 under H; orbits of k2 in W(k1)/C2 under H_{k1};
orbits of k3 in X(k1,k2) = {k3 in W(k1) cap W(k2) : |k1 k2 k3| odd} under H_{k1,k2}.
Stabilizers are generated by random Schreier generators and certified by an exact
Schreier-Sims order computation (sympy) equal to |parent stabilizer| / |orbit|.
Usage: python classify.py p q  -> writes results_p{p}q{q}.pkl next to this file.
"""
import sys, time, pickle, random
from pathlib import Path
import numpy as np
from sympy.combinatorics import Permutation, PermutationGroup
from sc_lib import Support, popcount, rref_int, reduce_int, rank_int, mat_apply
from orbits_nb import orbit_bfs

HERE = Path(__file__).resolve().parent
random.seed(12345)


class Level:
    """Orbits of a group (list of group elements `gens`) on a subspace of V_P/C2.

    basis: list of quotient-coordinate ints (dq bits) spanning the subspace.
    mask_fn: optional predicate on local coords selecting an invariant subset."""

    def __init__(self, sup, gens, basis, mask=None):
        self.sup, self.gens, self.basis = sup, gens, basis
        self.d = len(basis)
        # echelon with tags to express quotient vectors in local coords
        ech = []
        for i, b in enumerate(basis):
            r = b | (1 << (sup.dq + i))
            for pv, e in ech:
                if (r >> pv) & 1:
                    r ^= e
            low = r & ((1 << sup.dq) - 1)
            assert low
            pv = low.bit_length() - 1
            for e in ech:
                if (e[1] >> pv) & 1:
                    e[1] ^= r
            ech.append([pv, r])
        self.ech = ech
        self.qmats = [sup.quot_matrix(g) for g in gens]
        self.lmats = np.array([[self.local(mat_apply(qm, b)) for b in basis] for qm in self.qmats],
                              dtype=np.int64).reshape(len(gens), self.d)
        if mask is None:
            mask = np.ones(1 << self.d, dtype=np.bool_)
        self.orb, self.par, self.gu, self.reps, self.sizes = orbit_bfs(self.lmats, self.d, mask)

    def local(self, qc):
        tag = 0
        dq = self.sup.dq
        for pv, e in self.ech:
            if (qc >> pv) & 1:
                qc ^= e & ((1 << dq) - 1)
                tag ^= e >> dq
        assert qc == 0, "not in subspace"
        return tag

    def to_quot(self, lc):
        return mat_apply(self.basis, lc)

    def transporter(self, y):
        """Group element t with t(rep) = y (as a tuple acting on F_2^s)."""
        sup = self.sup
        t = tuple(1 << i for i in range(sup.s))
        chain = []
        while self.par[y] >= 0:
            chain.append(int(self.gu[y]))
            y = int(self.par[y])
        # y = gen[c0] gen[c1] ... gen[c_last] (rep)
        for k in reversed(chain):
            t = Support.gmul(self.gens[k], t, sup.s)
        return t

    def stabilizer_gens(self, oi, parent_order, max_tries=400):
        """Generators of the stabilizer of reps[oi], certified by order."""
        sup = self.sup
        rep = int(self.reps[oi])
        size = int(self.sizes[oi])
        target = parent_order // size
        assert parent_order % size == 0
        if size == 1:
            return list(self.gens), target
        members = np.nonzero(self.orb == oi)[0]
        chosen = []
        perms = []
        order = 1
        tries = 0
        while order != target:
            tries += 1
            if tries > max_tries:
                raise RuntimeError("stabilizer generation did not converge")
            y = int(members[random.randrange(len(members))])
            k = random.randrange(len(self.gens))
            z = int(mat_apply(list(self.lmats[k]), y))
            ty = self.transporter(y)
            tz = self.transporter(z)
            h = Support.gmul(sup.ginv(tz), Support.gmul(self.gens[k], ty, sup.s), sup.s)
            if h == tuple(1 << i for i in range(sup.s)):
                continue
            # sanity: h fixes rep
            assert self.local(mat_apply(sup.quot_matrix(h), self.to_quot(rep))) == rep
            chosen.append(h)
            perms.append(Permutation(sup.perm(h)))
            if len(chosen) % 3 == 0 or len(chosen) > 20:
                order = PermutationGroup(perms).order()
                assert target % order == 0
        return chosen, target


def functional(sup, a, b):
    """Linear functional on V_P/C2 coords: c -> |lift(c) & a & b| mod 2 (a,b functions)."""
    f = 0
    ab = a & b
    for i, v in enumerate(sup.comp):
        if popcount(v & ab) & 1:
            f |= 1 << i
    return f


def kernel_basis(fun_list, basis_quot, sup):
    """Basis (quotient ints) of {c in span(basis_quot) : popcount(c & f) even for all f}."""
    # express functionals restricted to the given basis
    d = len(basis_quot)
    rows = []
    for f in fun_list:
        r = 0
        for i, b in enumerate(basis_quot):
            if popcount(b & f) & 1:
                r |= 1 << i
        rows.append(r)
    from sc_lib import nullspace_of_dot
    ker_local = nullspace_of_dot(rows, d)
    return [mat_apply(basis_quot, v) for v in ker_local]


def W_basis(sup, k1func, within=None):
    funs = [functional(sup, k1func, m) for m in sup.rm1]
    if within is None:
        within = [1 << i for i in range(sup.dq)]
    return kernel_basis(funs, within, sup)


def run(p, q, sup=None, tag=""):
    """sup may be a Support whose comp basis spans an H-invariant subspace of V_P/C2
    (then the classification is of triples inside that subspace)."""
    if sup is None:
        sup = Support(p, q)
    H = sup.group_order()
    t0 = time.time()
    L1 = Level(sup, sup.gens, [1 << i for i in range(sup.dq)])
    print(f"level1: {len(L1.reps)} orbits ({time.time()-t0:.1f}s)", flush=True)
    results = {"p": p, "q": q, "n": sup.n, "H": H, "level1": [], "triples": []}
    L2s = {}
    L3s = {}
    for i1, r1 in enumerate(L1.reps):
        r1 = int(r1)
        k1 = sup.lift(r1)
        st1, o1 = L1.stabilizer_gens(i1, H)
        Wb = W_basis(sup, k1)
        L2 = Level(sup, st1, Wb)
        L2s[i1] = (L2, o1)
        npairs = 0
        ntrip = 0
        for i2, r2l in enumerate(L2.reps):
            r2 = L2.to_quot(int(r2l))
            k2 = sup.lift(r2)
            Wb3 = W_basis(sup, k2, within=Wb)
            par = functional(sup, k1, k2)
            # local coords on Wb3; mask = odd parity
            parl = 0
            for j, b in enumerate(Wb3):
                if popcount(b & par) & 1:
                    parl |= 1 << j
            if parl == 0:
                continue
            npairs += 1
            d3 = len(Wb3)
            idx = np.arange(1 << d3, dtype=np.int64)
            # parity of popcount(idx & parl)
            x = idx & parl
            par_arr = np.zeros(1 << d3, dtype=np.int64)
            for j in range(d3):
                par_arr ^= (x >> j) & 1
            mask = par_arr.astype(np.bool_)
            st2, o2 = L2.stabilizer_gens(i2, o1)
            L3 = Level(sup, st2, Wb3, mask=mask)
            L3s[(i1, i2)] = (L3, o2)
            for i3, r3l in enumerate(L3.reps):
                r3 = L3.to_quot(int(r3l))
                o3 = o2 // int(L3.sizes[i3])
                results["triples"].append(((i1, i2, i3), (r1, r2, r3), o3))
                ntrip += 1
        results["level1"].append({"rep": r1, "orbit": int(L1.sizes[i1]), "stab": o1,
                                  "dimW": len(Wb), "l2orbits": len(L2.reps),
                                  "pairs_completable": npairs, "ordered_triples": ntrip})
        print(f"  k1 orbit {i1}: rep {r1} |orb|={int(L1.sizes[i1])} |stab|={o1} dimW={len(Wb)} "
              f"L2 orbits={len(L2.reps)} completable={npairs} ordered triples={ntrip} "
              f"({time.time()-t0:.1f}s)", flush=True)
    # ------------------------------------------------ S3 canonicalization
    def canon(qa, qb, qc):
        i1 = int(L1.orb[qa])
        t1 = L1.transporter(qa)
        ti = sup.ginv(t1)
        M = sup.quot_matrix(ti)
        a, b, c = mat_apply(M, qa), mat_apply(M, qb), mat_apply(M, qc)
        assert a == int(L1.reps[i1])
        L2, _ = L2s[i1]
        bl = L2.local(b)
        i2 = int(L2.orb[bl])
        t2 = L2.transporter(bl)
        M2 = sup.quot_matrix(sup.ginv(t2))
        b2, c2 = mat_apply(M2, b), mat_apply(M2, c)
        assert L2.local(b2) == int(L2.reps[i2])
        if (i1, i2) not in L3s:
            return None
        L3, _ = L3s[(i1, i2)]
        cl = L3.local(c2)
        i3 = int(L3.orb[cl])
        assert i3 >= 0
        return (i1, i2, i3)

    from itertools import permutations
    idx_of = {t[0]: j for j, t in enumerate(results["triples"])}
    classes = []
    seen = set()
    for j, (key, (qa, qb, qc), o3) in enumerate(results["triples"]):
        if key in seen:
            continue
        trip = (qa, qb, qc)
        members = set()
        for perm in permutations(range(3)):
            ck = canon(*(trip[pi] for pi in perm))
            assert ck is not None and ck in idx_of
            members.add(ck)
        seen |= members
        classes.append({"members": sorted(members), "rep": trip, "stab_H": o3,
                        "aut_order": 6 * o3 // len(members)})
    results["classes"] = classes
    print(f"ordered-triple orbits: {len(results['triples'])}, classes up to S3: {len(classes)} "
          f"({time.time()-t0:.1f}s)", flush=True)
    # count check: sum over ordered-triple orbits of |H|/|stab| = number of ordered triples
    results["total_ordered_triples"] = sum(H // o for _, _, o in results["triples"])
    out = HERE / f"results_p{p}q{q}{tag}.pkl"
    with open(out, "wb") as fh:
        pickle.dump(results, fh)
    print("wrote", out)
    return results, canon, sup


if __name__ == "__main__":
    run(int(sys.argv[1]), int(sys.argv[2]))
