"""Utilities for Boolean decreasing monomial CSS codes.

This module implements the monomial-ideal layer used by the
``[[16,3,2]]`` decreasing-monomial example in arXiv:1910.09333.
Monomials are represented by integer bitmasks: bit ``i`` is variable ``x_i``.

The closure implemented here is the divisibility/downward closure in the
Boolean monomial poset.  This is the part needed for the local fixtures and
small scans; Bardet's full decreasing order can be added as a stricter search
mode later.
"""
from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations
from math import comb
from typing import Iterable, Sequence

import numpy as np

from gate2code.ccz import compute_distances, f2_rank, verify_ch_conditions
from gate2code.gmatrix import GInfo
from gate2code.gf2 import to_gf2
from gate2code.identity import no_correction
from gate2code.z8_kernel import supports_ccz_kernel


Mask = int


@dataclass(frozen=True)
class MonomialCSSCode:
    """CSS code generated by monomial evaluation rows on the full Boolean cube."""

    m: int
    C2_masks: tuple[Mask, ...]
    C1_masks: tuple[Mask, ...]
    G_logical: np.ndarray
    G0: np.ndarray
    logical_masks: tuple[Mask, ...]
    z_logical_masks: tuple[Mask, ...] = ()
    metadata: dict | None = None

    @property
    def G(self) -> np.ndarray:
        return np.vstack([self.G_logical, self.G0]).astype(np.uint8) % 2

    @property
    def n(self) -> int:
        return 1 << self.m

    @property
    def k(self) -> int:
        return len(self.logical_masks)

    @property
    def s(self) -> int:
        return len(self.C2_masks)


def mask_degree(mask: Mask) -> int:
    return bin(int(mask)).count("1")


def mask_to_vars(mask: Mask, *, one_based: bool = True) -> tuple[int, ...]:
    offset = 1 if one_based else 0
    return tuple(i + offset for i in range(mask.bit_length() + 1) if (mask >> i) & 1)


def monomial_label(mask: Mask) -> str:
    vars_ = mask_to_vars(mask, one_based=True)
    if not vars_:
        return "1"
    return "".join(f"x{i}" for i in vars_)


def all_monomial_masks(m: int, max_degree: int | None = None) -> tuple[Mask, ...]:
    if max_degree is None:
        max_degree = m
    masks: list[Mask] = []
    for deg in range(max_degree + 1):
        for vars_ in combinations(range(m), deg):
            mask = 0
            for v in vars_:
                mask |= 1 << v
            masks.append(mask)
    return tuple(masks)


def monomial_eval(mask: Mask, m: int, points: Sequence[int] | None = None) -> np.ndarray:
    """Evaluate a squarefree monomial on ``F_2^m`` in integer point order."""
    vals = tuple(range(1 << m) if points is None else points)
    row = np.ones(len(vals), dtype=np.uint8)
    for idx, point in enumerate(vals):
        row[idx] = 1 if (int(point) & mask) == mask else 0
    return row


def monomial_eval_matrix(masks: Iterable[Mask], m: int) -> np.ndarray:
    masks = tuple(int(x) for x in masks)
    if not masks:
        return np.zeros((0, 1 << m), dtype=np.uint8)
    return np.array([monomial_eval(mask, m) for mask in masks], dtype=np.uint8)


def downward_closure(generators: Iterable[Mask]) -> tuple[Mask, ...]:
    """Return all divisors/submasks of the supplied monomials."""
    closed: set[Mask] = set()
    for gen in generators:
        sub = int(gen)
        while True:
            closed.add(sub)
            if sub == 0:
                break
            sub = (sub - 1) & int(gen)
    return tuple(sorted(closed, key=lambda x: (mask_degree(x), x)))


def is_downward_closed(masks: Iterable[Mask]) -> bool:
    mask_set = set(int(x) for x in masks)
    for mask in tuple(mask_set):
        sub = mask
        while True:
            if sub not in mask_set:
                return False
            if sub == 0:
                break
            sub = (sub - 1) & mask
    return True


def dual_monomial_masks(masks: Iterable[Mask], m: int) -> tuple[Mask, ...]:
    """Generator masks for the dual of a decreasing monomial code.

    A monomial ``b`` is orthogonal to every generator ``a`` iff ``a | b`` is not
    the full monomial for every ``a``.  For a decreasing monomial code, the
    allowed monomials again generate the dual.
    """
    full = (1 << m) - 1
    gens = tuple(int(x) for x in masks)
    allowed = [
        b
        for b in all_monomial_masks(m)
        if all((a | b) != full for a in gens)
    ]
    return tuple(sorted(allowed, key=lambda x: (mask_degree(x), x)))


def _validate_pair(C2_masks: Sequence[Mask], C1_masks: Sequence[Mask]) -> None:
    c2 = set(C2_masks)
    c1 = set(C1_masks)
    if not c2 <= c1:
        raise ValueError("C2 masks must be a subset of C1 masks")
    if not is_downward_closed(c2):
        raise ValueError("C2 masks are not downward closed")
    if not is_downward_closed(c1):
        raise ValueError("C1 masks are not downward closed")


def build_css_pair(
    m: int,
    C2_masks: Iterable[Mask],
    C1_masks: Iterable[Mask],
    *,
    logical_masks: Iterable[Mask] | None = None,
    z_logical_masks: Iterable[Mask] | None = None,
    metadata: dict | None = None,
) -> MonomialCSSCode:
    """Build ``G=[K;S]`` from monomial sets ``C2 subset C1``."""
    C2 = tuple(sorted(set(int(x) for x in C2_masks), key=lambda x: (mask_degree(x), x)))
    C1 = tuple(sorted(set(int(x) for x in C1_masks), key=lambda x: (mask_degree(x), x)))
    _validate_pair(C2, C1)
    if logical_masks is None:
        logical = tuple(x for x in C1 if x not in set(C2))
    else:
        logical = tuple(int(x) for x in logical_masks)
        if set(logical) != (set(C1) - set(C2)):
            raise ValueError("explicit logical masks must equal C1 \\ C2")
    z_logical = tuple(int(x) for x in (z_logical_masks or ()))
    G0 = monomial_eval_matrix(C2, m)
    K = monomial_eval_matrix(logical, m)
    return MonomialCSSCode(
        m=m,
        C2_masks=C2,
        C1_masks=C1,
        G_logical=K,
        G0=G0,
        logical_masks=logical,
        z_logical_masks=z_logical,
        metadata=dict(metadata or {}),
    )


def build_paper_16_3_2() -> MonomialCSSCode:
    """Reproduce the paper's decreasing-monomial ``[[16,3,2]]`` example."""
    # Paper variables x1..x4 are internal bits 0..3.
    one = 0
    x1, x2, x3, x4 = (1 << i for i in range(4))
    C2 = (one, x1, x2)
    logical = (x3, x4, x1 | x2)
    C1 = C2 + logical
    z_logical = (x1 | x2 | x4, x1 | x2 | x3, x3 | x4)
    return build_css_pair(
        4,
        C2,
        C1,
        logical_masks=logical,
        z_logical_masks=z_logical,
        metadata={"name": "paper_16_3_2_decreasing"},
    )


def span_weight_distribution(G: np.ndarray) -> dict[int, int]:
    G = np.asarray(G, dtype=np.uint8) % 2
    rows, n = G.shape
    counts: dict[int, int] = {}
    cur = np.zeros(n, dtype=np.uint8)
    prev_gray = 0
    counts[0] = 1
    for idx in range(1, 1 << rows):
        gray = idx ^ (idx >> 1)
        diff = gray ^ prev_gray
        bit = diff.bit_length() - 1
        cur ^= G[bit]
        wt = int(cur.sum())
        counts[wt] = counts.get(wt, 0) + 1
        prev_gray = gray
    return dict(sorted(counts.items()))


def column_indicator_truth_table(G: np.ndarray) -> np.ndarray:
    """Return the full-G column indicator truth table, modulo column multiplicity."""
    G = np.asarray(G, dtype=np.uint8) % 2
    r, n = G.shape
    f = np.zeros(1 << r, dtype=np.uint8)
    for j in range(n):
        idx = 0
        for bit in G[:, j]:
            idx = (idx << 1) | int(bit)
        f[idx] ^= 1
    return f


def anf_of_truth_table(f: np.ndarray) -> np.ndarray:
    """Möbius transform from truth table to Boolean ANF coefficients."""
    anf = np.asarray(f, dtype=np.uint8).copy()
    n = int(anf.size)
    r = (n.bit_length() - 1)
    if n != (1 << r):
        raise ValueError("truth table length must be a power of two")
    for bit in range(r):
        for idx in range(n):
            if (idx >> bit) & 1:
                anf[idx] ^= anf[idx ^ (1 << bit)]
    return anf


def anf_degree(anf: np.ndarray) -> int:
    return max((bin(idx).count("1") for idx, coeff in enumerate(anf) if coeff), default=-1)


def anf_degree_spectrum(anf: np.ndarray) -> dict[int, int]:
    spec: dict[int, int] = {}
    for idx, coeff in enumerate(anf):
        if coeff:
            deg = bin(idx).count("1")
            spec[deg] = spec.get(deg, 0) + 1
    return dict(sorted(spec.items()))


def anf_monomial_labels(anf: np.ndarray, *, max_terms: int | None = None) -> list[str]:
    labels = [monomial_label(idx) for idx, coeff in enumerate(anf) if coeff]
    labels.sort(key=lambda label: (0 if label == "1" else label.count("x"), label))
    return labels if max_terms is None else labels[:max_terms]


def indicator_analysis(G: np.ndarray, *, max_terms: int = 40) -> dict:
    """Summarize the column-indicator polynomial of a G-matrix."""
    G = np.asarray(G, dtype=np.uint8) % 2
    f = column_indicator_truth_table(G)
    anf = anf_of_truth_table(f)
    return {
        "rows": int(G.shape[0]),
        "n_columns": int(G.shape[1]),
        "indicator_weight_mod2": int(f.sum()),
        "repeated_columns_mod2_cancel": int(G.shape[1] - f.sum()),
        "anf_degree": int(anf_degree(anf)),
        "anf_degree_spectrum": anf_degree_spectrum(anf),
        "anf_terms_sample": anf_monomial_labels(anf, max_terms=max_terms),
    }


def logical_pairing_matrix(code: MonomialCSSCode) -> np.ndarray:
    if not code.z_logical_masks:
        return np.zeros((code.k, 0), dtype=np.uint8)
    full = (1 << code.m) - 1
    out = np.zeros((code.k, len(code.z_logical_masks)), dtype=np.uint8)
    for i, x in enumerate(code.logical_masks):
        for j, z in enumerate(code.z_logical_masks):
            out[i, j] = 1 if (x | z) == full else 0
    return out


def triple_overlap_terms(masks: Sequence[Mask], m: int) -> list[tuple[int, int, int]]:
    """Return logical-row triples with odd monomial overlap."""
    full = (1 << m) - 1
    out = []
    for i, j, k in combinations(range(len(masks)), 3):
        if (int(masks[i]) | int(masks[j]) | int(masks[k])) == full:
            out.append((i, j, k))
    return out


def qrm_ccz_terms(r: int, m: int) -> list[tuple[Mask, Mask, Mask]]:
    """CCZ cubic terms for QRM ``C2=RM(r-1,m), C1=RM(r,m)``.

    Logical rows are degree-``r`` monomials.  A triple has odd overlap exactly
    when the union of its variables is the full degree-``m`` monomial.
    """
    degree_r = tuple(mask for mask in all_monomial_masks(m, r) if mask_degree(mask) == r)
    full = (1 << m) - 1
    terms = []
    for a, b, c in combinations(degree_r, 3):
        if (a | b | c) == full:
            terms.append((a, b, c))
    return terms


def expected_qrm_dimension(r: int, m: int) -> int:
    return comb(m, r)


def analyze_code(code: MonomialCSSCode, *, run_native: bool = True, run_z8: bool = True) -> dict:
    G = code.G.astype(np.uint8)
    ch_ok, ch_fail = verify_ch_conditions(G, k=code.k) if code.k == 3 else (False, "k_not_3")
    dx, dz = compute_distances(G.astype(int), k=code.k)
    native = None
    z8 = None
    if code.k == 3 and run_native:
        nc = no_correction(G, k=3)
        native = {"found": nc.found, "status": nc.status, "n_T": nc.n_T, "n_Tdag": nc.n_Tdag}
    if code.k == 3 and run_z8:
        z8 = bool(supports_ccz_kernel(GInfo(G=to_gf2(G), k=3)))
    return {
        "name": (code.metadata or {}).get("name"),
        "m": code.m,
        "n": code.n,
        "k": code.k,
        "s": code.s,
        "rank_G": f2_rank(G.astype(int)),
        "rank_G0": f2_rank(code.G0.astype(int)),
        "dx": dx,
        "dz": dz,
        "C2_weight_distribution": span_weight_distribution(code.G0),
        "C1_weight_distribution": span_weight_distribution(monomial_eval_matrix(code.C1_masks, code.m)),
        "logical_masks": [monomial_label(x) for x in code.logical_masks],
        "z_logical_masks": [monomial_label(x) for x in code.z_logical_masks],
        "logical_pairing": logical_pairing_matrix(code).astype(int).tolist(),
        "odd_triples": triple_overlap_terms(code.logical_masks, code.m),
        "ch_ok": ch_ok,
        "ch_fail": ch_fail,
        "native_CI": native,
        "z8_kernel": z8,
        "indicator": indicator_analysis(G),
    }


def all_downward_closed_sets(m: int) -> list[tuple[Mask, ...]]:
    """Enumerate all divisibility-downward monomial ideals for small ``m``."""
    masks = list(all_monomial_masks(m))
    ideals: list[tuple[Mask, ...]] = []
    total = 1 << len(masks)
    for bits in range(total):
        chosen = [masks[i] for i in range(len(masks)) if (bits >> i) & 1]
        if is_downward_closed(chosen):
            ideals.append(tuple(sorted(chosen, key=lambda x: (mask_degree(x), x))))
    return ideals


def scan_small_decreasing_pairs(
    m: int,
    *,
    target_k: int = 3,
    max_results: int = 50,
    require_ch: bool = True,
    run_native: bool = False,
    run_z8: bool = False,
) -> list[dict]:
    """Scan small monomial-ideal pairs ``C2 subset C1``."""
    ideals = all_downward_closed_sets(m)
    out: list[dict] = []
    for C2 in ideals:
        c2 = set(C2)
        for C1 in ideals:
            if not c2 <= set(C1):
                continue
            if len(C1) - len(C2) != target_k:
                continue
            try:
                code = build_css_pair(m, C2, C1)
            except ValueError:
                continue
            if f2_rank(code.G.astype(int)) != len(C1):
                continue
            if require_ch:
                ch_ok, _ = verify_ch_conditions(code.G, k=target_k)
                if not ch_ok:
                    continue
            row = analyze_code(code, run_native=run_native, run_z8=run_z8)
            row["C2_masks"] = [monomial_label(x) for x in C2]
            row["C1_masks"] = [monomial_label(x) for x in C1]
            out.append(row)
            if len(out) >= max_results:
                return out
    return out
